# Generated by Django 2.2.6 on 2020-04-03 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_auto_20200403_1437'),
    ]


